### ISSUE TITLE
Task1: Understanding the specifications of Heavy Drones in TiHAN Testbed.

### ISSUE THREAD

**Issue by yuvrajmakkena** [TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G#1]

**Comment by yuvrajmakkena** [comment]
![image](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/40199249/ec711de1-d9a7-4a5a-bc10-3a89afd08396)

**Comment by yuvrajmakkena** [comment]
1. Get more details of payload, cameras, on board computer and  Battery Information of these drones @White-Devil09

**Comment by White-Devil09** [comment]
Tarot ZD850:
Power Module: DIY AttoPilot 180A
Motor: 38-42 motor (recommended at least 3508 motor)
             Multistar Elite 5008 330Kv (this motor can be used)
Prop: 12-16 inch CW CCW
ESC: 40-50A(2-6s) ; 40A (2-4S)
Flight control: DJI Naze-M Lite, DJI Naza-M V2, PixHawk, APM, 32-Bit CC3D/Naze using iNav (GPS required)
Battery: 2-6S Lipo
Item Weight : 1.54 kg

**Comment by White-Devil09** [comment]
EFT 610P10L 6 Axis:
Supply voltage: 12S
Maximum take-off weight: 25kg
Tank capacity : 10L
Full load weight : 27 KG
Recommended motor : X6 + 23inch
Recommended battery : 16000mah 12s
