### ISSUE TITLE
Task2: Understanding the specifications of 5G Modems in TiHAN Testbed.

### ISSUE THREAD

**Issue by yuvrajmakkena** [TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G#2]

**Comment by yuvrajmakkena** [comment]
1. Take Teltonica Modem and connect with your Raspi --( which will be a companion computer on drone.)
2. Connect a laptop to ILL Public line and run object detection pod in k8.
3. Detect the objects using the camera stream input from Drone-Raspi on object detection pod and send back inferenced data.

**Comment by yuvrajmakkena** [comment]
Object detection Pod yaml:
https://github.com/TiHAN-Hyderabad/dronecamera-stream-detection

**Comment by White-Devil09** [comment]
Teltonica Modem has the following issues

!) It is not established with IP even when sim card is inserted.
2) led at 5g is blinking indicating that sim card is detected but its data connection is not established --> [led indications](https://wiki.teltonika-networks.com/index.php?title=RUTX50_LEDs&mobileaction=toggle_view_desktop)
3) After firmware update RUTX50 is having issues with connection of 5G --> [issue link](https://community.teltonika.lt/t/rutx50-sim-internet-not-working/774)
4)There are no solutions for firmware version as dated by 26-09-2023 and firmware version is RUTX_R_00.07.04.5
5) Alternative for RUTX50 is [TRB500](https://teltonika-networks.com/products/gateways/trb500/)  --  here is product link [amazon link](https://www.amazon.in/Teltonika-TRB500-Ethernet-Interface-Configurable/dp/B0BTHCKT7K)

**Comment by White-Devil09** [comment]
changed APN settings of sim to auto now data connection got established.

**Comment by yuvrajmakkena** [comment]
Simulate the Heavy Drone + 5G + TiE-k8-object detection on a Drone-Raspi + 5G + Laptop-k8-object detection, But setup a temp laptop as TiE with object detection pod and Jio public IP, until Firewall is installed, to ensure safety.

**Comment by White-Devil09** [comment]
Drone connectivity with 5G is done  Jio TiE object detection need to be done

**Comment by White-Devil09** [comment]
Done
