### ISSUE TITLE
Task3: Deploy a Client Agent on drone companion computer to communicate with TiE.

### ISSUE THREAD

**Issue by yuvrajmakkena** [TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G#3]

**Comment by yuvrajmakkena** [comment]
- Drone-Raspi setup -- Done
   - Connected with Tetonika 5G Modem for Network -- with LAN
   - Raspi OS - running Client.py to capture frames from raspi camera

**Comment by White-Devil09** [comment]
Done
1 Connected with Tetonika 5G Modem for Network -- with LAN (Done)
![WhatsApp Image 2023-10-09 at 1 08 24 PM](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/116197384/69f9d13f-2598-438b-a00c-f5d931770ba0)

2 Solved the apt repository updates issue by changing the mirror. (will upload the sources list here) (Done)

3 Raspi OS - running Client.py to capture frames from raspi camera (Done)
![Screenshot from 2023-10-08 03-02-19](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/116197384/b41c7f20-553b-48e6-807a-02bde65f7541)

**Comment by White-Devil09** [comment]
Initial testing Images
![IMG_7789](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/116197384/b5171b1e-f377-40e9-a7b8-5fa6c1977e45)
![IMG_7770](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/116197384/647ccdfb-7baf-4fed-ad71-8a5559971dcd)
![IMG_7774](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/116197384/0f9d4ebe-63c5-45ae-b5fb-1a8fd34c5d4e)
![IMG_7775](https://github.com/TiHAN-Hyderabad/Enhancing-Heavy-Drone-Object-Detection-Using-5G/assets/116197384/586e9a9a-9477-4e78-a26d-fa6c78af5023)
